apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: retail-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: db-secrets
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_USER
      remoteRef:
        key: db-creds
        property: mysql_user
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: db-creds
        property: mysql_password
    - secretKey: PG_USER
      remoteRef:
        key: db-creds
        property: pg_user
    - secretKey: PG_PASSWORD
      remoteRef:
        key: db-creds
        property: pg_password