apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-app

resources:
  - ../../base/retail-store-sample-app/deploy/kubernetes/base

patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
  - path: patch-resources.yaml
    target:
      kind: StatefulSet